Include xlsx.full.min.js in index.html, not in app.module.ts due to errors
It seems that when we try to import XLSX in app.module.ts, we get this
error: Uncaught TypeError: Buffer is not a constructor

The XLSX package is version < 1, and there is no ng6 mentions in the docs
(only mentions ng 2-5). So we go with a workaround.